### ISSUE TITLE
Bots won't talk to me

### ISSUE THREAD

**Issue by benkline** [forstaathletics/textsecure-node#1]
don't know if it is part of the snafu of getting out of sync that we worked through earlier - but bots won't talk to me anymore. ☹️

**Comment by mayfield** [comment]
Those things are designed to only respond a fraction of the time.  Not actionable.

**Comment by benkline** [comment]
they're talking to everyone else

![image](https://user-images.githubusercontent.com/1417632/33848240-54ac61b6-de6a-11e7-8311-b6fe048803eb.png)

**Comment by mayfield** [comment]
Keychange handling not implemented on those bots.
